// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXZqTgcBEagRamV5F0s4qdUYR-D_LqvJ8',
    appId: '1:1016300705042:android:3b2ed114cf780446664fcb',
    messagingSenderId: '1016300705042',
    projectId: 'medconnect-r71',
    storageBucket: 'medconnect-r71.firebasestorage.app',
  );
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKC1eS1WxyuWJPivLVSqTWZAgv_t3TzjA',
    appId: '1:1016300705042:web:faec710dfa3b890f664fcb',
    messagingSenderId: '1016300705042',
    projectId: 'medconnect-r71',
    authDomain: 'medconnect-r71.firebaseapp.com',
    storageBucket: 'medconnect-r71.firebasestorage.app',
    measurementId: 'G-Y1NR9KEL65',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCKC1eS1WxyuWJPivLVSqTWZAgv_t3TzjA',
    appId: '1:1016300705042:web:967223444506f06f664fcb',
    messagingSenderId: '1016300705042',
    projectId: 'medconnect-r71',
    authDomain: 'medconnect-r71.firebaseapp.com',
    storageBucket: 'medconnect-r71.firebasestorage.app',
    measurementId: 'G-87D4E3TKG9',
  );
}
